title: Rodrigo Iglesias | Personal blog
description: > # this means to ignore newlines until "baseurl:"
  Education, music, technology and trips
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://areidz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rodrigo Iglesias # add your name
author-img: rodrigo-iglesias.jpg # add your photo
about-author: I am a curious person, always hungry to keep learning.  # add description
social-twitter: RigleOP # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Areidz # add your Github handle
social-flickr: Areidz # add your Flickr handle
social-linkedin: Rigle # add your Linkedin handle
social-email: rigle@pm.me # add your Email address

# Disqus
discus-identifier: areidzme # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
